# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='pic',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYDa9jD5oAfDsrSOC4exu-MVUWqdL37rCMpiC7uMQi2IhxSvCS', max_length=500),
        ),
        migrations.AddField(
            model_name='directors',
            name='pic',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYDa9jD5oAfDsrSOC4exu-MVUWqdL37rCMpiC7uMQi2IhxSvCS'),
        ),
        migrations.AddField(
            model_name='movies',
            name='pic',
            field=models.URLField(blank=True, default='http://icons.iconarchive.com/icons/guillendesign/variations-3/256/Default-Icon-icon.png', max_length=500),
        ),
        migrations.AddField(
            model_name='rating',
            name='pic',
            field=models.URLField(blank=True, default='http://icons.iconarchive.com/icons/guillendesign/variations-3/256/Default-Icon-icon.png', max_length=500),
        ),
    ]
