# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0005_actors_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='directors',
            name='gender',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
