# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0008_directors_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.URLField(blank=True, default='/', max_length=500),
        ),
    ]
