# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0010_auto_20171020_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
    ]
