# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0011_auto_20171020_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdb',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='actors',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='directors',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
    ]
