# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0012_auto_20171020_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=2500)),
                ('points', models.IntegerField()),
                ('email', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOVIE_REVIEW.movies')),
            ],
        ),
        migrations.RemoveField(
            model_name='directors',
            name='phone',
        ),
    ]
