# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0013_auto_20171111_1519'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set([('mov_id', 'email')]),
        ),
    ]
