# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOVIE_REVIEW', '0014_auto_20171111_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='userrating',
            field=models.FloatField(default=0),
        ),
    ]
